---
- name: Offline tls tool | install unzip pakage
  package:
    name: unzip
    state: present

- name: Offline tls tool | Create download tree
  file:
    state: directory
    dest: "{{ item }}"
  with_items: "{{ seach_guard_create_dir_list }}"
  delegate_to: "{{keyring_host}}"
  remote_user: "{{ remote_keyring_host_user }}"

- name: Offline tls tool | Download search guard offline-tls-tool
  get_url:
    url: "{{ seach_guard_download_url }}"
    dest: "{{ seach_guard_path_download }}"
  register: search_guard_download_zip
  delegate_to: "{{keyring_host}}"
  remote_user: "{{ remote_keyring_host_user }}"

- name: Offline tls tool | unzip Seach Guard offline-tls-tool
  unarchive:
    src: "{{ search_guard_download_zip.dest }}"
    dest: "{{ seach_guard_path_offline_tls_tool }}"
    remote_src: yes
  register: search_guard_download_unarchive
  delegate_to: "{{keyring_host}}"
  remote_user: "{{ remote_keyring_host_user }}"
  when: not search_guard_download_zip.changed
  # Hi guest from the future i know this not is strange
  # but check the code befor remove it