---
- name: main | install offline tls tool
  import_tasks: download_offline_tls_tool.yml

- name: main | configure offline tls tool
  import_tasks: configure_offline_tls_tool.yml
 
- name: main | create certificate
  import_tasks: create_certificate.yml

- name: main | create cert
  import_tasks: install_cert.yml

- name: main | install seachguard
  import_tasks: install_seachguard.yml
  