---
- name: main | install offline tls tool
  import_tasks: download_offline_tls_tool.yml

- name: main | configure offline tls tool
  import_tasks: configure_offline_tls_tool.yml
 
- name: main | create certificate
  import_tasks: create_certificate.yml

- name: main | create certificate
  import_tasks: install_cert.yaml

- name: main | install seachguard plugin
  import_tasks: install_seachguard_plugin.yml
  