---
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled

- name: restart elasticsearch
  become: yes
  service: 
    name: elasticsearch
    state: restarted
    enabled: yes
  register: es_restarted

- name: stopped elasticsearch
  become: yes
  service: 
    name: elasticsearch
    state: stopped
  register: es_stopped