---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
platforms:
  - name: instance-1
    image: "bk_centos_preInstall"
    flavor: o1.highcpu-spot.x2
    groups:
      - elk
  - name: instance-2
    image: "bk_centos_preInstall"
    flavor: o1.highcpu-spot.x2
    groups:
      - elk
  - name: instance-3
    image: "bk_centos_preInstall"
    flavor: o1.highcpu-spot.x2
    groups:
      - elk
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
verifier:
  name: goss
