---
- name: run the main role
  hosts: all
  become: yes
  pre_tasks:
    - name: create master_list
      set_fact:
        temp_var: |
          cluster_master:
          {% for server in groups['elk'] %}
            - {{ hostvars[server].ansible_hostname }}
          {% endfor %}

    - name: set definitive master list
      set_fact:
        master_list: "{{ temp_var | from_yaml }}"

    - name: debug var
      debug:
        msg: "{{ master_list.cluster_master }}"
  roles:
  - role: geerlingguy.java
    java_packages:
      - java-11-openjdk
      # - openjdk-11-jdk
  - role: elastic.elasticsearch
    es_version: "7.3.1"
    es_instance_name: "{{ ansible_hostname }}"
    es_heap_size: 2g
    es_start_service: false
    xpack.installed: false
    es_java_install: false
    update_java: false
    es_config:
      cluster.name: "molecule"

      http.port: 9200
      transport.tcp.port: 9300
      network.host: 0.0.0.0
      node.data: true
      node.master: true
      discovery.seed_hosts: "{{ groups['elk'] }}"
      cluster.initial_master_nodes: "{{ master_list.cluster_master }}"
      xpack.security.enabled: false
      searchguard.ssl.transport.pemcert_filepath: /etc/elasticsearch/cert/{{ ansible_hostname }}.pem
      searchguard.ssl.transport.pemkey_filepath: /etc/elasticsearch/cert/{{ ansible_hostname }}.key
      searchguard.ssl.transport.pemkey_password: V3r1s3cr3tp4ssw0rd
      searchguard.ssl.transport.pemtrustedcas_filepath: /etc/elasticsearch/cert/root-ca.pem
      searchguard.ssl.transport.enforce_hostname_verification: false
      searchguard.ssl.transport.resolve_hostname: false
      searchguard.ssl.http.enabled: true
      searchguard.ssl.http.pemcert_filepath: /etc/elasticsearch/cert/{{ ansible_hostname }}_http.pem
      searchguard.ssl.http.pemkey_filepath: /etc/elasticsearch/cert/{{ ansible_hostname }}_http.key
      searchguard.ssl.http.pemkey_password: V3r1s3cr3tp4ssw0rd
      searchguard.ssl.http.pemtrustedcas_filepath: /etc/elasticsearch/cert/root-ca.pem
      searchguard.nodes_dn:
      - CN=*.novalocal,OU=Ops,O={{ seach_guard_basic_domain.o }},DC={{seach_guard_basic_domain.dc1}},DC={{seach_guard_basic_domain.dc2}}
      searchguard.authcz.admin_dn:
      - CN=attilio.agreco.it,OU=Ops,O={{ seach_guard_basic_domain.o }},DC={{seach_guard_basic_domain.dc1}},DC={{seach_guard_basic_domain.dc2}}
  - role: ansible-seachguard
  post_tasks:
    - synchronize:
        src: "/var/seachguard/cert/client/"
        dest: "/home/centos/"